apiVersion: v1
kind: ConfigMap
metadata:
  name: sresim-config
data:
  config.yaml: |
    server:
      port: 8080
      read_timeout: 10s
      write_timeout: 10s
      idle_timeout: 60s
    
    metrics:
      enabled: true
      path: /metrics
      port: 8080
    
    scenarios:
      default_duration: 5m
      max_concurrent: 3
      cleanup_interval: 1m
    
    circuit_breaker:
      failure_threshold: 5
      reset_timeout: 30s
      half_open_timeout: 10s
    
    rate_limiter:
      requests_per_second: 10
      burst_size: 20
    
    resource_limits:
      max_cpu_percent: 80
      max_memory_bytes: 512Mi
      max_disk_io_bytes: 1Gi
    
    network:
      max_latency_ms: 1000
      error_rate_percent: 5
      partition_probability: 0.1 