name: ArgoCD CI

on:
  push:
    branches:
      - main
      

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/sresim:latest .
      
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/sresim:latest

      # Removed the separate "update infra repo" section

